sudo: required
dist: trusty
services:
- docker
before_install:
- docker pull qiwihui/hiwifi-ss-compile
- mkdir -p build
- docker run -d --name hiwifi -v `pwd`/compile.sh:/mnt/compile.sh qiwihui/hiwifi-ss-compile
script:
- docker exec -i hiwifi sh /mnt/compile.sh
- for f in $(docker exec -it hiwifi bash -c "ls /mnt/build/shadowsocks-mipsel/ss-*"); do docker cp hiwifi:`echo $f | sed 's/\\r//g'` ./build/; done
- for f in $(docker exec -it hiwifi bash -c "ls /mnt/build/shadowsocks-mipsel/obfs-*"); do docker cp hiwifi:`echo $f | sed 's/\\r//g'` ./build/; done
- ls -al ./build/
deploy:
  provider: releases

  file_glob: true
  file: 
    - "build/ss-*"
    - "build/obfs-*"
  skip_cleanup: true
  on:
    tags: true
